In [3]:
import pandas as pd

In [4]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1459 non-null   int64  
 1   MSSubClass     1459 non-null   int64  
 2   MSZoning       1455 non-null   object 
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64  
 5   Street         1459 non-null   object 
 6   Alley          107 non-null    object 
 7   LotShape       1459 non-null   object 
 8   LandContour    1459 non-null   object 
 9   Utilities      1457 non-null   object 
 10  LotConfig      1459 non-null   object 
 11  LandSlope      1459 non-null   object 
 12  Neighborhood   1459 non-null   object 
 13  Condition1     1459 non-null   object 
 14  Condition2     1459 non-null   object 
 15  BldgType       1459 non-null   object 
 16  HouseStyle     1459 non-null   object 
 17  OverallQual    1459 non-null   int64  
 18  OverallC

In [7]:
train.shape

(1460, 81)

In [8]:
#no target in test
test.shape

(1459, 80)

In [9]:
train.select_dtypes(include=['object']).describe()

MSZoning Street Alley LotShape  ...  Fence MiscFeature SaleType SaleCondition
count      1460   1460    91     1460  ...    281          54     1460          1460
unique        5      2     2        4  ...      4           4        9             6
top          RL   Pave  Grvl      Reg  ...  MnPrv        Shed       WD        Normal
freq       1151   1454    50      925  ...    157          49     1267          1198

[4 rows x 43 columns]

In [10]:
train.describe()

Id   MSSubClass  ...       YrSold      SalePrice
count  1460.000000  1460.000000  ...  1460.000000    1460.000000
mean    730.500000    56.897260  ...  2007.815753  180921.195890
std     421.610009    42.300571  ...     1.328095   79442.502883
min       1.000000    20.000000  ...  2006.000000   34900.000000
25%     365.750000    20.000000  ...  2007.000000  129975.000000
50%     730.500000    50.000000  ...  2008.000000  163000.000000
75%    1095.250000    70.000000  ...  2009.000000  214000.000000
max    1460.000000   190.000000  ...  2010.000000  755000.000000

[8 rows x 38 columns]

# Identifying Missing Values

In [11]:
train.select_dtypes(include=['object']).describe().T.assign(missing_pct=train.apply(lambda x:(len(x)-x.count())/len(x)))

count unique      top  freq  missing_pct
MSZoning       1460      5       RL  1151     0.000000
Street         1460      2     Pave  1454     0.000000
Alley            91      2     Grvl    50     0.937671
LotShape       1460      4      Reg   925     0.000000
LandContour    1460      4      Lvl  1311     0.000000
Utilities      1460      2   AllPub  1459     0.000000
LotConfig      1460      5   Inside  1052     0.000000
LandSlope      1460      3      Gtl  1382     0.000000
Neighborhood   1460     25    NAmes   225     0.000000
Condition1     1460      9     Norm  1260     0.000000
Condition2     1460      8     Norm  1445     0.000000
BldgType       1460      5     1Fam  1220     0.000000
HouseStyle     1460      8   1Story   726     0.000000
RoofStyle      1460      6    Gable  1141     0.000000
RoofMatl       1460      8  CompShg  1434     0.000000
Exterior1st    1460     15  VinylSd   515     0.000000
Exterior2nd    1460     16  VinylSd   504     0.000000
MasVnrType     1452      4     None   864     0.005479
ExterQual      1460      4       TA   906     0.000000
ExterCond      1460      5       TA  1282     0.000000
Foundation     1460      6    PConc   647     0.000000
BsmtQual       1423      4       TA   649     0.025342
BsmtCond       1423      4       TA  1311     0.025342
BsmtExposure   1422      4       No   953     0.026027
BsmtFinType1   1423      6      Unf   430     0.025342
BsmtFinType2   1422      6      Unf  1256     0.026027
Heating        1460      6     GasA  1428     0.000000
HeatingQC      1460      5       Ex   741     0.000000
CentralAir     1460      2        Y  1365     0.000000
Electrical     1459      5    SBrkr  1334     0.000685
KitchenQual    1460      4       TA   735     0.000000
Functional     1460      7      Typ  1360     0.000000
FireplaceQu     770      5       Gd   380     0.472603
GarageType     1379      6   Attchd   870     0.055479
GarageFinish   1379      3      Unf   605     0.055479
GarageQual     1379      5       TA  1311     0.055479
GarageCond     1379      5       TA  1326     0.055479
PavedDrive     1460      3        Y  1340     0.000000
PoolQC            7      3       Gd     3     0.995205
Fence           281      4    MnPrv   157     0.807534
MiscFeature      54      4     Shed    49     0.963014
SaleType       1460      9       WD  1267     0.000000
SaleCondition  1460      6   Normal  1198     0.000000

In [12]:
train.select_dtypes(include=['int64']).describe().T.assign(missing_pct=train.apply(lambda x:(len(x)-x.count())/len(x)))

count           mean  ...       max  missing_pct
Id             1460.0     730.500000  ...    1460.0          0.0
MSSubClass     1460.0      56.897260  ...     190.0          0.0
LotArea        1460.0   10516.828082  ...  215245.0          0.0
OverallQual    1460.0       6.099315  ...      10.0          0.0
OverallCond    1460.0       5.575342  ...       9.0          0.0
YearBuilt      1460.0    1971.267808  ...    2010.0          0.0
YearRemodAdd   1460.0    1984.865753  ...    2010.0          0.0
BsmtFinSF1     1460.0     443.639726  ...    5644.0          0.0
BsmtFinSF2     1460.0      46.549315  ...    1474.0          0.0
BsmtUnfSF      1460.0     567.240411  ...    2336.0          0.0
TotalBsmtSF    1460.0    1057.429452  ...    6110.0          0.0
1stFlrSF       1460.0    1162.626712  ...    4692.0          0.0
2ndFlrSF       1460.0     346.992466  ...    2065.0          0.0
LowQualFinSF   1460.0       5.844521  ...     572.0          0.0
GrLivArea      1460.0    1515.463699  ...    5642.0          0.0
BsmtFullBath   1460.0       0.425342  ...       3.0          0.0
BsmtHalfBath   1460.0       0.057534  ...       2.0          0.0
FullBath       1460.0       1.565068  ...       3.0          0.0
HalfBath       1460.0       0.382877  ...       2.0          0.0
BedroomAbvGr   1460.0       2.866438  ...       8.0          0.0
KitchenAbvGr   1460.0       1.046575  ...       3.0          0.0
TotRmsAbvGrd   1460.0       6.517808  ...      14.0          0.0
Fireplaces     1460.0       0.613014  ...       3.0          0.0
GarageCars     1460.0       1.767123  ...       4.0          0.0
GarageArea     1460.0     472.980137  ...    1418.0          0.0
WoodDeckSF     1460.0      94.244521  ...     857.0          0.0
OpenPorchSF    1460.0      46.660274  ...     547.0          0.0
EnclosedPorch  1460.0      21.954110  ...     552.0          0.0
3SsnPorch      1460.0       3.409589  ...     508.0          0.0
ScreenPorch    1460.0      15.060959  ...     480.0          0.0
PoolArea       1460.0       2.758904  ...     738.0          0.0
MiscVal        1460.0      43.489041  ...   15500.0          0.0
MoSold         1460.0       6.321918  ...      12.0          0.0
YrSold         1460.0    2007.815753  ...    2010.0          0.0
SalePrice      1460.0  180921.195890  ...  755000.0          0.0

[35 rows x 9 columns]

In [13]:
train.select_dtypes(include=['float64']).describe().T.assign(missing_pct=train.apply(lambda x:(len(x)-x.count())/len(x)))

count         mean         std  ...     75%     max  missing_pct
LotFrontage  1201.0    70.049958   24.284752  ...    80.0   313.0     0.177397
MasVnrArea   1452.0   103.685262  181.066207  ...   166.0  1600.0     0.005479
GarageYrBlt  1379.0  1978.506164   24.689725  ...  2002.0  2010.0     0.055479

[3 rows x 9 columns]

In [14]:
train.select_dtypes(include=['object']).describe().T.assign(missing_pct=train.apply(lambda x:(len(x)-x.count())/len(x)))

count unique      top  freq  missing_pct
MSZoning       1460      5       RL  1151     0.000000
Street         1460      2     Pave  1454     0.000000
Alley            91      2     Grvl    50     0.937671
LotShape       1460      4      Reg   925     0.000000
LandContour    1460      4      Lvl  1311     0.000000
Utilities      1460      2   AllPub  1459     0.000000
LotConfig      1460      5   Inside  1052     0.000000
LandSlope      1460      3      Gtl  1382     0.000000
Neighborhood   1460     25    NAmes   225     0.000000
Condition1     1460      9     Norm  1260     0.000000
Condition2     1460      8     Norm  1445     0.000000
BldgType       1460      5     1Fam  1220     0.000000
HouseStyle     1460      8   1Story   726     0.000000
RoofStyle      1460      6    Gable  1141     0.000000
RoofMatl       1460      8  CompShg  1434     0.000000
Exterior1st    1460     15  VinylSd   515     0.000000
Exterior2nd    1460     16  VinylSd   504     0.000000
MasVnrType     1452      4     None   864     0.005479
ExterQual      1460      4       TA   906     0.000000
ExterCond      1460      5       TA  1282     0.000000
Foundation     1460      6    PConc   647     0.000000
BsmtQual       1423      4       TA   649     0.025342
BsmtCond       1423      4       TA  1311     0.025342
BsmtExposure   1422      4       No   953     0.026027
BsmtFinType1   1423      6      Unf   430     0.025342
BsmtFinType2   1422      6      Unf  1256     0.026027
Heating        1460      6     GasA  1428     0.000000
HeatingQC      1460      5       Ex   741     0.000000
CentralAir     1460      2        Y  1365     0.000000
Electrical     1459      5    SBrkr  1334     0.000685
KitchenQual    1460      4       TA   735     0.000000
Functional     1460      7      Typ  1360     0.000000
FireplaceQu     770      5       Gd   380     0.472603
GarageType     1379      6   Attchd   870     0.055479
GarageFinish   1379      3      Unf   605     0.055479
GarageQual     1379      5       TA  1311     0.055479
GarageCond     1379      5       TA  1326     0.055479
PavedDrive     1460      3        Y  1340     0.000000
PoolQC            7      3       Gd     3     0.995205
Fence           281      4    MnPrv   157     0.807534
MiscFeature      54      4     Shed    49     0.963014
SaleType       1460      9       WD  1267     0.000000
SaleCondition  1460      6   Normal  1198     0.000000

# Dealing with Missing Values

In [15]:
#Dropping columns that that have more than 75% missing values
train.dropna(axis=1, thresh=int(0.75*len(train)),inplace=True)
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 76 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [16]:
#Doing the same with missing data(2)
fillna_list=pd.DataFrame(train.isnull().any())

In [17]:
fillna_list.reset_index()

index      0
0              Id  False
1      MSSubClass  False
2        MSZoning  False
3     LotFrontage   True
4         LotArea  False
..            ...    ...
71         MoSold  False
72         YrSold  False
73       SaleType  False
74  SaleCondition  False
75      SalePrice  False

[76 rows x 2 columns]

In [18]:
fillna_list1=list(fillna_list[fillna_list[0]==True].index)
fillna_list1

['LotFrontage',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [19]:
nb_list=['LotFrontage','MasVnrArea','GarageYrBlt']
str_list1=set(fillna_list1)^set(nb_list)
str_list2=list(str_list1)
str_list2

['Electrical',
 'MasVnrType',
 'BsmtFinType1',
 'GarageQual',
 'GarageFinish',
 'GarageCond',
 'BsmtCond',
 'BsmtQual',
 'GarageType',
 'BsmtFinType2',
 'BsmtExposure']

In [20]:
#numrical_fillna
for i in nb_list:
    train[i]=train[i].fillna(value=train[i].mean())

In [21]:
#str_fillna
for i in str_list2:
    train[i]=train[i].fillna(value='None')

In [22]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 76 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [23]:
train_object=list(train.select_dtypes(include=['object']).columns)

#One Hot Encoding

In [24]:
dummies_object=pd.get_dummies(train.select_dtypes(include=['object']))
dummies_object

MSZoning_C (all)  ...  SaleCondition_Partial
0                    0  ...                      0
1                    0  ...                      0
2                    0  ...                      0
3                    0  ...                      0
4                    0  ...                      0
...                ...  ...                    ...
1455                 0  ...                      0
1456                 0  ...                      0
1457                 0  ...                      0
1458                 0  ...                      0
1459                 0  ...                      0

[1460 rows x 244 columns]

#Ensuring Proper Data Types

In [25]:
train['GarageYrBlt'].value_counts()

1978.506164    81
2005.000000    65
2006.000000    59
2004.000000    53
2003.000000    50
               ..
1908.000000     1
1927.000000     1
1933.000000     1
1900.000000     1
1906.000000     1
Name: GarageYrBlt, Length: 98, dtype: int64

In [26]:
import numpy as np
import datetime as dt
train['GarageYrBlt']=train['GarageYrBlt'].apply(np.int)
train['GarageYrBlt'].astype(str).apply(lambda x: pd.to_datetime(x,format='%Y'))

0      2003-01-01
1      1976-01-01
2      2001-01-01
3      1998-01-01
4      2000-01-01
          ...    
1455   1999-01-01
1456   1978-01-01
1457   1941-01-01
1458   1950-01-01
1459   1965-01-01
Name: GarageYrBlt, Length: 1460, dtype: datetime64[ns]

In [27]:
train.drop(columns=train_object,inplace=True)

In [28]:
train_target=train['SalePrice']

In [29]:
new_train=train.drop(columns='SalePrice')

# test

In [30]:
test.dropna(axis=1, thresh=int(0.75*len(test)),inplace=True)
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1459 non-null   int64  
 1   MSSubClass     1459 non-null   int64  
 2   MSZoning       1455 non-null   object 
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64  
 5   Street         1459 non-null   object 
 6   LotShape       1459 non-null   object 
 7   LandContour    1459 non-null   object 
 8   Utilities      1457 non-null   object 
 9   LotConfig      1459 non-null   object 
 10  LandSlope      1459 non-null   object 
 11  Neighborhood   1459 non-null   object 
 12  Condition1     1459 non-null   object 
 13  Condition2     1459 non-null   object 
 14  BldgType       1459 non-null   object 
 15  HouseStyle     1459 non-null   object 
 16  OverallQual    1459 non-null   int64  
 17  OverallCond    1459 non-null   int64  
 18  YearBuil

In [31]:
fillna_listA=pd.DataFrame(test.isnull().any())
fillna_listA

0
Id             False
MSSubClass     False
MSZoning        True
LotFrontage     True
LotArea        False
...              ...
MiscVal        False
MoSold         False
YrSold         False
SaleType        True
SaleCondition  False

[75 rows x 1 columns]

In [32]:
fillna_listB=list(fillna_listA[fillna_listA[0]==True].index)
len(fillna_listB)

28

In [33]:
test_object_nan=list(test[fillna_listB].select_dtypes(include=['object']).columns)
test_object_nan

['MSZoning',
 'Utilities',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'KitchenQual',
 'Functional',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'SaleType']

In [34]:
test_other_nan=list(test[fillna_listB].select_dtypes(include=['float64']).columns)
test_other_nan

['LotFrontage',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'BsmtFullBath',
 'BsmtHalfBath',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea']

In [35]:
for i in test_object_nan:
    test[i]=test[i].fillna(value='None')

In [36]:
for i in test_other_nan:
    test[i]=test[i].fillna(value=test[i].mean())

In [37]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1459 non-null   int64  
 1   MSSubClass     1459 non-null   int64  
 2   MSZoning       1459 non-null   object 
 3   LotFrontage    1459 non-null   float64
 4   LotArea        1459 non-null   int64  
 5   Street         1459 non-null   object 
 6   LotShape       1459 non-null   object 
 7   LandContour    1459 non-null   object 
 8   Utilities      1459 non-null   object 
 9   LotConfig      1459 non-null   object 
 10  LandSlope      1459 non-null   object 
 11  Neighborhood   1459 non-null   object 
 12  Condition1     1459 non-null   object 
 13  Condition2     1459 non-null   object 
 14  BldgType       1459 non-null   object 
 15  HouseStyle     1459 non-null   object 
 16  OverallQual    1459 non-null   int64  
 17  OverallCond    1459 non-null   int64  
 18  YearBuil

In [38]:
import numpy as np
import datetime as dt
test['GarageYrBlt']=test['GarageYrBlt'].apply(np.int)
test['GarageYrBlt'].astype(str).apply(lambda x: pd.to_datetime(x,format='%Y'))

0      1961-01-01
1      1958-01-01
2      1997-01-01
3      1998-01-01
4      1992-01-01
          ...    
1454   1977-01-01
1455   1970-01-01
1456   1960-01-01
1457   1977-01-01
1458   1993-01-01
Name: GarageYrBlt, Length: 1459, dtype: datetime64[ns]

In [39]:
test_object=list(test.select_dtypes(include=['object']).columns)

In [40]:
dummies_object1=pd.get_dummies(test.select_dtypes(include=['object']))
dummies_object1

MSZoning_C (all)  ...  SaleCondition_Partial
0                    0  ...                      0
1                    0  ...                      0
2                    0  ...                      0
3                    0  ...                      0
4                    0  ...                      0
...                ...  ...                    ...
1454                 0  ...                      0
1455                 0  ...                      0
1456                 0  ...                      0
1457                 0  ...                      0
1458                 0  ...                      0

[1459 rows x 234 columns]

In [41]:
test.drop(columns=test_object,inplace=True)

In [42]:
test.shape

(1459, 37)

# feature_select

In [43]:
train_feature=pd.concat(objs=[new_train,dummies_object],axis=1)
train_feature

Id  MSSubClass  ...  SaleCondition_Normal  SaleCondition_Partial
0        1          60  ...                     1                      0
1        2          20  ...                     1                      0
2        3          60  ...                     1                      0
3        4          70  ...                     0                      0
4        5          60  ...                     1                      0
...    ...         ...  ...                   ...                    ...
1455  1456          60  ...                     1                      0
1456  1457          20  ...                     1                      0
1457  1458          70  ...                     1                      0
1458  1459          20  ...                     1                      0
1459  1460          20  ...                     1                      0

[1460 rows x 281 columns]

In [44]:
test_feature=pd.concat(objs=[test,dummies_object1],axis=1)
test_feature

Id  MSSubClass  ...  SaleCondition_Normal  SaleCondition_Partial
0     1461          20  ...                     1                      0
1     1462          20  ...                     1                      0
2     1463          60  ...                     1                      0
3     1464          60  ...                     1                      0
4     1465         120  ...                     1                      0
...    ...         ...  ...                   ...                    ...
1454  2915         160  ...                     1                      0
1455  2916         160  ...                     0                      0
1456  2917          20  ...                     0                      0
1457  2918          85  ...                     1                      0
1458  2919          60  ...                     1                      0

[1459 rows x 271 columns]

In [45]:
#find the feature in both train and test
both_feature=list(set(train_feature)&set(test_feature))
both_feature

['SaleType_ConLD',
 'BsmtHalfBath',
 'EnclosedPorch',
 'Foundation_CBlock',
 'Exterior2nd_CBlock',
 'LotFrontage',
 'BsmtFinSF1',
 'BldgType_1Fam',
 'Exterior2nd_CmentBd',
 'SaleCondition_Abnorml',
 'LowQualFinSF',
 'RoofMatl_Tar&Grv',
 'RoofMatl_CompShg',
 'TotRmsAbvGrd',
 '3SsnPorch',
 'Neighborhood_IDOTRR',
 'SaleType_COD',
 'SaleType_Oth',
 'BsmtQual_TA',
 'HouseStyle_1.5Unf',
 'BedroomAbvGr',
 'BsmtQual_Gd',
 'Electrical_SBrkr',
 'ExterCond_Gd',
 'PavedDrive_Y',
 'LandContour_Lvl',
 'LotShape_IR1',
 'BldgType_TwnhsE',
 'Exterior2nd_Brk Cmn',
 'GarageCars',
 'BsmtCond_Gd',
 'BsmtExposure_Av',
 'RoofMatl_WdShake',
 'TotalBsmtSF',
 'BsmtFinType2_LwQ',
 'HeatingQC_Fa',
 'Condition2_Artery',
 'LotConfig_Corner',
 'Exterior1st_AsphShn',
 'Exterior2nd_VinylSd',
 'PavedDrive_P',
 'Neighborhood_SawyerW',
 'Functional_Min1',
 'Neighborhood_Gilbert',
 'ScreenPorch',
 'HouseStyle_SLvl',
 'BsmtCond_TA',
 'BsmtQual_Fa',
 'Functional_Maj1',
 'BsmtExposure_Mn',
 'Functional_Min2',
 'GarageType_Ca

In [46]:
new_train_feature=train_feature[both_feature]
new_test_feature=test_feature[both_feature]

In [47]:
new_train_feature

SaleType_ConLD  BsmtHalfBath  ...  GarageType_Detchd  Electrical_FuseA
0                  0             0  ...                  0                 0
1                  0             1  ...                  0                 0
2                  0             0  ...                  0                 0
3                  0             0  ...                  1                 0
4                  0             0  ...                  0                 0
...              ...           ...  ...                ...               ...
1455               0             0  ...                  0                 0
1456               0             0  ...                  0                 0
1457               0             0  ...                  0                 0
1458               0             0  ...                  0                 1
1459               0             0  ...                  0                 0

[1460 rows x 264 columns]

In [48]:
new_test_feature

SaleType_ConLD  BsmtHalfBath  ...  GarageType_Detchd  Electrical_FuseA
0                  0           0.0  ...                  0                 0
1                  0           0.0  ...                  0                 0
2                  0           0.0  ...                  0                 0
3                  0           0.0  ...                  0                 0
4                  0           0.0  ...                  0                 0
...              ...           ...  ...                ...               ...
1454               0           0.0  ...                  0                 0
1455               0           0.0  ...                  0                 0
1456               0           0.0  ...                  1                 0
1457               0           1.0  ...                  0                 0
1458               0           0.0  ...                  0                 0

[1459 rows x 264 columns]

In [49]:
#standard data, make predict more accuracy
from sklearn.preprocessing import StandardScaler
#write standard rule
scaler=StandardScaler().fit(new_train_feature)
#use standard rule
Std_train_feature=scaler.transform(new_train_feature)
Std_train_feature

array([[-0.07875671, -0.24106104, -0.3593249 , ...,  0.51813339,
        -0.60055892, -0.26232433],
       [-0.07875671,  3.94880935, -0.3593249 , ...,  0.51813339,
        -0.60055892, -0.26232433],
       [-0.07875671, -0.24106104, -0.3593249 , ...,  0.51813339,
        -0.60055892, -0.26232433],
       ...,
       [-0.07875671, -0.24106104, -0.3593249 , ...,  0.51813339,
        -0.60055892, -0.26232433],
       [-0.07875671, -0.24106104,  1.47378925, ...,  0.51813339,
        -0.60055892,  3.81207488],
       [-0.07875671, -0.24106104, -0.3593249 , ...,  0.51813339,
        -0.60055892, -0.26232433]])

In [50]:
scaler1=StandardScaler().fit(new_test_feature)
Std_test_feature=scaler1.transform(new_test_feature)
Std_test_feature

array([[-0.108578  , -0.258526  , -0.3607383 , ..., -1.79693781,
        -0.60612308, -0.2624204 ],
       [-0.108578  , -0.258526  , -0.3607383 , ...,  0.55650229,
        -0.60612308, -0.2624204 ],
       [-0.108578  , -0.258526  , -0.3607383 , ...,  0.55650229,
        -0.60612308, -0.2624204 ],
       ...,
       [-0.108578  , -0.258526  , -0.3607383 , ...,  0.55650229,
         1.64982992, -0.2624204 ],
       [-0.108578  ,  3.7064464 , -0.3607383 , ...,  0.55650229,
        -0.60612308, -0.2624204 ],
       [-0.108578  , -0.258526  , -0.3607383 , ...,  0.55650229,
        -0.60612308, -0.2624204 ]])

In [51]:
#split the train dataset
from sklearn.model_selection import train_test_split
x_train,y_train,x_target,y_target=train_test_split(Std_train_feature,train_target,test_size=0.3)

# Decision Tree

In [52]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
tree_parameters = {"criterion":["mse", "friedman_mse",'mae'], "splitter":["best", "random"], "min_samples_split":[4,5,6], "max_depth":[2,4,6]}
tree = DecisionTreeRegressor()
clf1 = GridSearchCV(tree, tree_parameters, cv=5)
clf1.fit(x_train, x_target)
clf1.best_params_

{'criterion': 'friedman_mse',
 'max_depth': 6,
 'min_samples_split': 6,
 'splitter': 'best'}

In [53]:
train_tree=DecisionTreeRegressor(criterion='mae',splitter='best',max_depth=4,min_samples_split=5)
train_tree.fit(x_train,x_target)
predict_tree=train_tree.predict(y_train)
predict_tree

array([128000. , 183000. ,  86250. , 122000. , 122000. , 230000. ,
       230000. , 122000. , 179900. , 179900. , 179900. , 270000. ,
       183000. , 140000. , 230000. ,  86250. , 270000. , 179900. ,
       232000. , 179900. , 745000. , 183000. , 140000. , 122000. ,
       179900. , 270000. , 122000. , 179900. , 230000. , 136905. ,
       145000. , 122000. , 745000. , 232000. , 122000. , 163000. ,
       331150. , 122000. , 122000. , 331150. , 136905. , 122000. ,
       140000. , 230000. , 140000. , 179900. , 270000. , 122000. ,
       122000. , 230000. , 179900. , 179900. , 122000. , 145000. ,
       183000. , 270000. , 270000. , 179900. , 230000. , 183000. ,
       122000. , 183000. , 183000. , 179900. , 179900. , 128000. ,
       122000. , 183000. , 183000. , 122000. , 179900. , 270000. ,
       183000. , 230000. , 122000. , 179900. , 122000. , 140000. ,
       122000. , 230000. , 122000. , 232000. , 179900. , 163000. ,
       183000. , 179900. , 179900. , 122000. , 136905. , 12200

In [54]:
from sklearn.metrics import mean_squared_error, r2_score
# Explained variance score: 1 is perfect prediction 
#  R2 决定系数（拟合优度）
# 模型越好：r2→1
# 模型越差：r2→0
print('Variance score: %.2f' % r2_score(y_target, predict_tree))

Variance score: 0.51


# Random Forest

In [55]:
# from sklearn.ensemble import RandomForestRegressor
# forest_parameters = {"criterion":["mse","friedman_mse",'mae'],"n_estimators":[100,200,300], "min_samples_split":[2,3,4]}
# random_forest = RandomForestRegressor()
# clf2 = GridSearchCV(random_forest, forest_parameters, cv=5)
# clf2.fit(x_train,x_target)
# clf2.best_params_

In [56]:
from sklearn.ensemble import RandomForestRegressor
forest=RandomForestRegressor(criterion='mse')
forest.fit(x_train, x_target)
predict_forest=forest.predict(y_train)
predict_forest

array([134726.01, 158577.39,  82708.58, 143938.5 ,  94321.  , 259945.48,
       302750.77, 115096.55, 177767.46, 160293.66, 195310.82, 266217.9 ,
       159530.4 , 137835.  , 234323.95,  98170.81, 359540.54, 201689.24,
       227246.17, 169086.7 , 371005.97, 169868.72, 148301.  , 128347.41,
       163605.49, 338895.4 , 122113.58, 174342.77, 224933.97, 156185.69,
       158008.09, 130177.6 , 303608.01, 220267.6 , 122839.19, 178344.93,
       316334.04, 102606.37, 132384.5 , 333063.99, 195044.37, 105190.75,
       148458.62, 216783.8 , 104392.75, 172118.32, 247246.24, 121319.14,
       110945.58, 307311.54, 188662.44, 187118.07,  97600.  , 145485.74,
       195511.46, 212745.67, 266445.91, 157661.76, 240988.47, 199409.08,
       130209.34, 190723.07, 200835.16, 131788.92, 167051.92, 146829.65,
       115182.27, 177580.65, 211257.62, 104441.08, 167753.06, 248616.71,
       139513.04, 372070.88, 118080.45, 180632.06, 136399.59, 152767.33,
       113183.32, 240682.16, 123062.08, 284526.79, 

In [57]:
# Explained variance score: 1 is perfect prediction 
#  R2 决定系数（拟合优度）
# 模型越好：r2→1
# 模型越差：r2→0
print('Variance score: %.2f' % r2_score(y_target, predict_forest))

Variance score: 0.88


# Support Vector Machine

In [58]:
#tried linear and rbf
from sklearn.svm import SVR
SVReg=SVR(kernel ='linear')
SVReg.fit(x_train, x_target)
predict_SVR=SVReg.predict(y_train)
predict_SVR

array([153347.17805726, 157652.58882057, 138123.19018271, 168974.19321348,
       147660.32606718, 168962.6040338 , 181985.53119653, 146023.19771054,
       163835.63208998, 164566.35618903, 162517.17798616, 183609.11258949,
       149907.17769636, 156792.66106751, 176944.95910269, 135472.29539279,
       185247.05429383, 173038.84555616, 179066.98997045, 161069.45973339,
       176526.67596348, 173166.16995119, 158752.2855183 , 154426.10482901,
       159892.79018343, 184539.70114744, 151835.08799643, 153759.54881965,
       177440.55920137, 155092.81268547, 161523.20117204, 161466.29037746,
       175573.32865783, 169800.20346397, 153106.79860748, 175812.49893372,
       182894.90762068, 145496.82592976, 153224.04226745, 168307.79538718,
       150884.81718717, 146402.76824368, 159342.20317743, 177130.36539857,
       138905.12443659, 164485.46668688, 179532.25214982, 143459.61173213,
       146696.84504866, 173038.04947376, 172447.75867382, 164396.17486821,
       143760.43093393, 1

In [59]:
#SVR bad
print('Variance score: %.2f' % r2_score(y_target, predict_SVR))

Variance score: 0.18


# Multilayer Perceptron

In [60]:
from sklearn.neural_network import MLPRegressor
mlp=MLPRegressor(hidden_layer_sizes=(4000, ),activation='logistic',solver='lbfgs')
mlp.fit(x_train, x_target)
predict_mlp=mlp.predict(y_train)
predict_mlp

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


array([147180.52134744, 158932.69038579,  87492.65053614, 152603.67259358,
        93044.5228067 , 305399.17624382, 296589.96968173, 145699.40023002,
       218232.24834459, 125498.96693748, 293587.52255392, 293996.14074764,
       188898.31637192, 131414.2478485 , 244120.97201633,  89112.31299804,
       397034.58225501, 314228.4654133 , 224869.51502108, 168110.27038806,
       409498.16555598, 171734.37965632, 122400.33048328, 148037.87791558,
       170180.93694201, 338158.10247338, 100429.82180087, 179037.16055083,
       212867.11736405, 167070.12345352, 158821.39704638, 150263.55238502,
       293767.27089443, 390329.51078351, 135572.4588487 , 189160.72225022,
       278974.22926341,  93729.57812474, 127080.63624388, 399842.07484916,
       137604.24015834, 122716.06106874, 164057.80124031, 200705.96429775,
       156540.65964641, 155825.40125328, 259653.30582551, 112748.56281794,
       101600.27768111, 260033.27432599, 185350.63273303, 200575.34037189,
        80416.65737292, 1

In [61]:
print('Variance score: %.2f' % r2_score(y_target, predict_mlp))

Variance score: 0.79


# Stochastic Gradient Descent

In [62]:
from sklearn.linear_model import SGDRegressor

In [63]:
sgd=SGDRegressor()
sgd.fit(x_train, x_target)
predict_sgd=sgd.predict(y_train)
predict_sgd

array([  2661372.49926338,   1868734.94032127,   1645427.51943114,
        -3757043.08385711,    368796.69627202,   8079117.01668919,
         -385687.94549901,  -5860021.39152812,  -2146150.01944519,
        -3736497.86757367,  -4006862.12730411,    112589.42735399,
         6560803.65255706,  -1711834.62039192,    196043.82196661,
         2076451.19853227,   1481815.57914382,   -690951.90779239,
         -822199.36344598,  -1423022.82240725,  -6095779.58148587,
          440741.5434546 ,   -730985.92642912,   -533667.1308329 ,
        -1426276.81727793,    691788.67855427,  -1985750.09140329,
        -4747842.53897569,  -1071828.81944311,    817584.89011754,
         1075976.00976643,    105034.56531846,   1870335.5375677 ,
        -2943968.19059417,   -583431.46367974,    907970.06209848,
          143182.68864566,   4340163.59554474,   2690817.22946998,
          778247.30110432,   4033739.99191289,   1882340.67125089,
        -3452164.30659764,   -503122.99434433, -11100198.24419

In [64]:
print('Variance score: %.2f' % r2_score(y_target, predict_sgd))

Variance score: -1874.32


# Linear Regression

In [65]:
from sklearn.linear_model import LinearRegression

In [66]:
#bad
lr=LinearRegression()
lr.fit(x_train, x_target)
predict_lr=lr.predict(y_train)
predict_lr

array([ 1.63637500e+05,  1.77541500e+05,  5.61815000e+04,  1.37797500e+05,
        8.67895000e+04,  2.79141500e+05,  3.20293500e+05,  1.11621500e+05,
        2.36549500e+05,  1.05925500e+05,  2.35845500e+05,  3.07781500e+05,
        1.20517500e+05,  1.42581500e+05,  2.20165500e+05,  6.74615000e+04,
        3.82533500e+05,  2.76741500e+05,  2.30789500e+05,  1.74997500e+05,
        4.32773500e+05,  1.60293500e+05,  1.37573500e+05,  1.23701500e+05,
        1.59557500e+05,  3.76965500e+05,  1.18853500e+05,  1.83237500e+05,
        2.19717500e+05,  1.47141500e+05,  1.64981500e+05,  1.51045500e+05,
        3.15813500e+05,  3.55461500e+05,  1.48021500e+05,  2.00517500e+05,
        3.18533500e+05,  1.01445500e+05,  1.12133500e+05,  3.02789500e+05,
        1.49957500e+05,  1.05701500e+05,  1.30757500e+05,  2.05829500e+05,
        2.76535000e+04,  1.61317500e+05,  2.67685500e+05,  9.23575000e+04,
        9.77655000e+04,  2.38005500e+05,  1.87589500e+05,  2.11205500e+05,
        8.64695000e+04,  

In [67]:
print('Variance score: %.2f' % r2_score(y_target, predict_sgd))

Variance score: -1874.32


In [68]:
#stacked valid
import numpy as np
stacked_vaild=np.column_stack((predict_tree,predict_forest,predict_mlp))

In [69]:
#predict_testset
predict_tree1=train_tree.predict(Std_test_feature)
predict_forest1=forest.predict(Std_test_feature)
predict_mlp1=mlp.predict(Std_test_feature)

In [70]:
#stacked test
stacked_test=np.column_stack((predict_tree1,predict_forest1,predict_mlp1))

In [71]:
#grid search and coress valid 5 times with forest
from sklearn.model_selection import GridSearchCV
forest_parameters = {"criterion":["mse","friedman_mse",'mae'],"n_estimators":[100,200,300], "min_samples_split":[2,3,4]}
random_forest = RandomForestRegressor()
clf2 = GridSearchCV(random_forest, forest_parameters, cv=5)
clf2.fit(stacked_vaild,y_target)
clf2.best_params_

{'criterion': 'mae', 'min_samples_split': 4, 'n_estimators': 300}

In [72]:
#stacking random forest
#create model
stacking_model=RandomForestRegressor(criterion='mae',min_samples_split=4,n_estimators=200)
#train_model
stacking_model.fit(stacked_vaild,y_target)
#predict_model
predict_stacking=stacking_model.predict(stacked_test)
predict_stacking

array([138168.25 , 169172.25 , 180177.995, ..., 160906.875, 112169.5  ,
       222259.76 ])